Repository DIT112-V19/group-07, pull requests merged in 2019-05, with the labels that each got.

#15 Add templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Sprint #1

#24 Basic obstacle avoidence
  .DS_Store
  Arduino/MainSketch/MainSketch.ino
Labels: Coding, Sprint #1

#25 Update MainSketch.ino
  Arduino/MainSketch/MainSketch.ino
Labels: Sprint #4

#28 Normal mobility mode (code-template)
  Arduino/MainSketch/MainSketch.ino
  ArduinoRemote2/.idea/codeStyles/Project.xml
  ArduinoRemote2/.idea/encodings.xml
  ArduinoRemote2/.idea/vcs.xml
  ArduinoRemote2/build.gradle
  ArduinoRemote2/gradle/wrapper/gradle-wrapper.properties
Labels: Sprint #6
